config/routes.rb
Rails.application.routes.draw do

  root 'sessions#destroy'

  resources :users, :tasks

  get  '/login'  => 'sessions#new'
  post '/login'  => 'sessions#create'
  get  '/logout' => 'sessions#destroy', :to => redirect('/login')

end

app/models/task.rb
class Task < ActiveRecord::Base

  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base

  # Links security
  has_secure_password

  has_many :tasks

  # Password and Email Parameters Check
  validates :name, :presence => { message: "Must enter a name for the account" }

  validates :password, :length => { in: 6..20, message: "password has to be between 6 and 20 characters" },
                       :presence => { message: "password can't be blank" }
  validates :password, confirmation:true
  validates :password_confirmation, presence: true

  validates :email, presence: true,
                    :uniqueness => { message: "email is already used" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method(:current_user)

  def authorize
    redirect_to '/login' unless current_user
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to('/tasks')
    else
      redirect_to('/login')
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to('/login')
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :authorize

  def index
    @tasks = Task.all
  end

  def new
      @task = Task.new
      @user = User.find(session[:user_id])
  end

  def create
    task = Task.new(task_params)
    task.user_id = current_user.id
    task.completed = false
    if task.save
      redirect_to('/tasks')
    else
      redirect_to('tasks/new')
    end

  end

  def show
    id = current_user.id
    @tasks = Task.find(id)
    @user = current_user

    redirect_to('/tasks')
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @user = User.find(current_user.id)

    if @task.update(task_params)
      redirect_to '/tasks'
    else
      redirect_to '/tasks', :notice => { :success => "Edit failed, please try again!" }
    end
  end

  def destroy
    task = Task.find(params[:id])
    task.delete
    redirect_to('/tasks')
  end


  def task_params
    params.require(:task).permit(
      :user,
      :priority,
      :content,
      :completed
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize, except: [:new , :create]
  before_action :authorize, except: [:new, :create]

  # Admin Only User Listing
  # Front Page should be here
  def index
    @users = User.all
    @current_user = User.find_by_id(session[:current_user_id])
  end

  # New User Obj
  def new
    @user = User.new
  end

  # User Signup
  def create
    user = User.new(user_params)
    if user.save
      redirect_to('/login')
    else
      redirect_to('/users/new')
    end
  end

  # User Profile
  def show
    @user = User.find(params[:id])
  end

  # Update User Profile
  def update
    @user = User.find(params[:id])
  end

  def destroy
  end

  private
  # User information fetch for batabase
  def user_params
    params.require(:user).permit(
      :image_url,
      :name,
      :email,
      :password,
      :password_confirmation
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NeedARuby</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="nav-bar" style="text-align: center; padding-bottom: 20px;">
    <div style="display: inline;">
        <% if current_user %>
      <div class="logged-in">
          Signed in as <%= current_user.name %> | <%= link_to "logout", "/logout" %> | <%= link_to "New Task!", "/tasks/new" %>
      </div>
        <% else %>

      <div class="logged-out">
          <%= link_to "Login", "/login" %>  <%= link_to "Sign up", "/users/new" %>
      </div>
          <% end %>
    </div>
  </div>

  <%= yield %>

</body>
</html>

app/views/tasks/edit.html.erb
<div class="task-update-form">

  <%= form_for @task do |f| %>

    <%= link_to "X", task_path, method: :delete, data: {confirm: "Delete this task permanently?"} %>
    Priority: <%= f.select :priority, [['Want', 'want'], ['Need', 'need']] %>
    Task:     <%= f.text_area  :content  %>
    <%= f.submit "Complete Edit" %>

  <% end %>

</div>

app/views/tasks/index.html.erb
<div class="header">
  <h1>Welcome to Taskify!</h1>
  <p> List it | Learn it | Love it </p>
</div>

<!-- Container for all 3 lists -->
<div class="lists-container">
  <ul>
    <li>

      <div class="need-tasks">
        <ul>
          <h2> DO IT NOW </h2>
          <% @tasks.select{|task| task.priority == "need" }.each do |task| %>
                <li>

                  <div class="task">
                    <p><%= task.content %>
                      <% if task.user_id == current_user.id %>
                        <%= link_to "edit" , edit_task_path(id: task.id) %>
                      <% end %>
                    </p>
                  </div>

                </li>
          <% end %>
        </ul>
      </div>

    </li>

    <li>

      <div class="want-tasks">
        <ul>
          <h2> Meh, you can always do it later... </h2>
          <% @tasks.select{|task| task.priority == "want" }.each do |task| %>
                <li>

                  <div class="task">
                    <p><%= task.content %>
                      <% if task.user_id == current_user.id %>
                        <%= link_to "edit" , edit_task_path(id: task.id) %>
                      <% end %>
                    </p>
                  </div>

                </li>
          <% end %>
        </ul>
      </div>

    </li>

    <li>

      <div class="completed-tasks">
        <ul>
          <h2> Well done </h2>
          <% @tasks.select{|task| task.completed == true }.each do |task| %>
            <li>

              <div class="task">
                <p><%= task.content %>
                  <% if task.user_id == current_user.id %>
                    <%= link_to "edit" , edit_task_path(id: task.id) %>
                  <% end %>
                </p>
              </div>

            </li>
          <% end %>
        </ul>
      </div>

    </li>

  </ul>

</div>

app/views/tasks/new.html.erb
<div class="new_task">

  <h2> Create A New Task </h2>

  <%= form_for @task, url: '/tasks' do |f| %>
    <ul>
      <li> Priority: <%= f.select :priority, [['Want', 'want'], ['Need', 'need']] %> </li>
      <li> Task:     <%= f.text_field :content  %> </li>
      <li>           <%= f.submit     "Create Task"  %> </li>
    </ul>
  <% end %>

</div>

app/views/tasks/show.html.erb
<div class="tasks">
  <ul>
    <li>
      <% if @user.id == true %>
          <%= @tasks.priority %>
          <%= @task.content %>
      <% else %>
        <% "Permission Denied" %>
      <% end %>
    </li>
  </ul>
</div>

app/views/tasks/update.html.erb
<div class="task-editor">
  <ul>
    <li>
      <% if @user.id == true %>
          <%= @task.title %>
          <%= @task.content %>
      <% else %>
        <% "Permission Denied" %>
      <% end %>
    </li>
  </ul>
</div>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete,
                                     data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="create_user">
  <%= stylesheet_link_tag 'sign_up', media: 'print, screen' %>
  <h1>Sign up</h1>

  <%= form_for :user, url: '/users' do |f| %>
    <ul>
      <li> Profile Picture url: <%= f.text_field  :image_url %>            </li>
      <li> Name:               <%= f.text_field   :name %>                 </li>
      <li> Email:             <%= f.text_field    :email %>                </li>
      <li> Password:         <%= f.password_field :password %>             </li>
      <li> Confirm Password:<%= f.password_field  :password_confirmation %></li>
      <li> Bio:            <%= f.text_field       :bio %>                  </li>
      <li>                <%= f.submit "Signup" %>                         </li>
    </ul>
  <% end %>

</div>